{"termsofuse"=>"http://boardgamegeek.com/xmlapi/termsofuse",
 "item"=>
  [{"type"=>"boardgame",
    "id"=>"15062",
    "thumbnail"=>["http://cf.geekdo-images.com/images/pic70547_t.jpg"],
    "image"=>["http://cf.geekdo-images.com/images/pic70547.jpg"],
    "name"=>
     [{"type"=>"primary", "sortindex"=>"1", "value"=>"Shadows over Camelot"},
      {"type"=>"alternate",
       "sortindex"=>"5",
       "value"=>"Les Chevaliers de la Table Ronde"},
      {"type"=>"alternate", "sortindex"=>"1", "value"=>"Cienie nad Camelot"},
      {"type"=>"alternate",
       "sortindex"=>"1",
       "value"=>"Schatten über Camelot"},
      {"type"=>"alternate", "sortindex"=>"1", "value"=>"シャドウズ・オーバー・キャメロット"}],
    "description"=>
     ["Shadows over Camelot is a cooperative/semi-cooperative hand management and deduction-based board game for 3-7 players.&#10;&#10;Each player represents a knight of
    "yearpublished"=>[{"value"=>"2005"}],
    "minplayers"=>[{"value"=>"3"}],
    "maxplayers"=>[{"value"=>"7"}],
    "poll"=>
     [{"name"=>"suggested_numplayers",
       "title"=>"User Suggested Number of Players",
       "totalvotes"=>"199",
       "results"=>
        [{"numplayers"=>"1",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"1"},
            {"value"=>"Recommended", "numvotes"=>"9"},
            {"value"=>"Not Recommended", "numvotes"=>"117"}]},
         {"numplayers"=>"2",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"0"},
            {"value"=>"Recommended", "numvotes"=>"13"},
            {"value"=>"Not Recommended", "numvotes"=>"124"}]},
         {"numplayers"=>"3",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"5"},
            {"value"=>"Recommended", "numvotes"=>"52"},
            {"value"=>"Not Recommended", "numvotes"=>"104"}]},
         {"numplayers"=>"4",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"30"},
            {"value"=>"Recommended", "numvotes"=>"111"},
            {"value"=>"Not Recommended", "numvotes"=>"26"}]},
         {"numplayers"=>"5",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"98"},
            {"value"=>"Recommended", "numvotes"=>"74"},
            {"value"=>"Not Recommended", "numvotes"=>"1"}]},
         {"numplayers"=>"6",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"112"},
            {"value"=>"Recommended", "numvotes"=>"54"},
            {"value"=>"Not Recommended", "numvotes"=>"7"}]},
         {"numplayers"=>"7",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"102"},
            {"value"=>"Recommended", "numvotes"=>"57"},
            {"value"=>"Not Recommended", "numvotes"=>"16"}]},
         {"numplayers"=>"7+",
          "result"=>
           [{"value"=>"Best", "numvotes"=>"6"},
            {"value"=>"Recommended", "numvotes"=>"17"},
            {"value"=>"Not Recommended", "numvotes"=>"74"}]}]},
      {"name"=>"suggested_playerage",
       "title"=>"User Suggested Player Age",
       "totalvotes"=>"61",
       "results"=>
        [{"result"=>
           [{"value"=>"2", "numvotes"=>"0"},
            {"value"=>"3", "numvotes"=>"0"},
            {"value"=>"4", "numvotes"=>"0"},
            {"value"=>"5", "numvotes"=>"0"},
            {"value"=>"6", "numvotes"=>"1"},
            {"value"=>"8", "numvotes"=>"8"},
            {"value"=>"10", "numvotes"=>"34"},
            {"value"=>"12", "numvotes"=>"14"},
            {"value"=>"14", "numvotes"=>"4"},
            {"value"=>"16", "numvotes"=>"0"},
            {"value"=>"18", "numvotes"=>"0"},
            {"value"=>"21 and up", "numvotes"=>"0"}]}]},
      {"name"=>"language_dependence",
       "title"=>"Language Dependence",
       "totalvotes"=>"76",
       "results"=>
        [{"result"=>
           [{"level"=>"1",
             "value"=>"No necessary in-game text",
             "numvotes"=>"0"},
            {"level"=>"2",
             "value"=>
              "Some necessary text - easily memorized or small crib sheet",
             "numvotes"=>"5"},
            {"level"=>"3",
             "value"=>"Moderate in-game text - needs crib sheet or paste ups",
             "numvotes"=>"54"},
            {"level"=>"4",
             "value"=>
              "Extensive use of text - massive conversion needed to be playable",
             "numvotes"=>"17"},
            {"level"=>"5",
             "value"=>"Unplayable in another language",
             "numvotes"=>"0"}]}]}],
    "playingtime"=>[{"value"=>"90"}],
    "minage"=>[{"value"=>"10"}],
    "link"=>
     [{"type"=>"boardgamecategory", "id"=>"1022", "value"=>"Adventure"},
      {"type"=>"boardgamecategory", "id"=>"1039", "value"=>"Deduction"},
      {"type"=>"boardgamecategory", "id"=>"1010", "value"=>"Fantasy"},
      {"type"=>"boardgamecategory", "id"=>"1035", "value"=>"Medieval"},
      {"type"=>"boardgamecategory", "id"=>"1082", "value"=>"Mythology"},
      {"type"=>"boardgamemechanic",
       "id"=>"2023",
       "value"=>"Co-operative Play"},
      {"type"=>"boardgamemechanic", "id"=>"2040", "value"=>"Hand Management"},
      {"type"=>"boardgamemechanic", "id"=>"2019", "value"=>"Partnerships"},
      {"type"=>"boardgamemechanic",
       "id"=>"2685",
       "value"=>"Player Elimination"},
      {"type"=>"boardgamemechanic",
       "id"=>"2015",
       "value"=>"Variable Player Powers"},
      {"type"=>"boardgamefamily",
       "id"=>"22839",
       "value"=>
        "The Legend of King Arthur and the Knights of the Round Table"},
      {"type"=>"boardgamefamily",
       "id"=>"21898",
       "value"=>"Shadows over Camelot"},
      {"type"=>"boardgameexpansion",
       "id"=>"35704",
       "value"=>"Shadows over Camelot: Merlin's Company"},
      {"type"=>"boardgameexpansion",
       "id"=>"20857",
       "value"=>"Shadows over Camelot: Sir Bedivere, the 8th Knight"},
      {"type"=>"boardgameimplementation",
       "id"=>"129904",
       "value"=>"Shadows over Camelot: The Card Game"},
      {"type"=>"boardgamedesigner", "id"=>"1727", "value"=>"Bruno Cathala"},
      {"type"=>"boardgamedesigner", "id"=>"295", "value"=>"Serge Laget"},
      {"type"=>"boardgameartist", "id"=>"11886", "value"=>"Julien Delval"},
      {"type"=>"boardgamepublisher",
       "id"=>"1027",
       "value"=>"Days of Wonder"}]}]}